//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppTrue.Models
{
    using System;
    using System.Collections.Generic;
    using System.Security.Policy;
    using System.Web.Management;
    using static WebAppTrue.Controllers.ChatRoomEmploeesController;

    public partial class ChatRoomEmploee
    {
        public int id { get; set; }
        public Nullable<int> idChatRoom { get; set; }
        public Nullable<int> idEmplyee { get; set; }
    
        public virtual ChatRoom ChatRoom { get; set; }
        public virtual Emplyee Emplyee { get; set; }

        
    }

    public partial class ChatRoomEmploee
    {
        public ChatRoomEmploee(SimpleER simer)
        {
            this.id = simer.id;
            this.idChatRoom = simer.idChatRoom;
            this.idEmplyee = simer.idEmplyee;
        }
        public ChatRoomEmploee() { }
    }

    


}
